// Package flowgen generates a Vanilla JS state engine from a parsed CoreFlow
// document. The output is a self-contained IIFE that can be injected into any
// standalone CoreUI HTML page.
//
// The generated engine uses a simple pub/sub pattern: a plain object holds
// state values, and a map of subscriber callbacks is notified on every
// mutation. There are no external dependencies.
package flowgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/valueforvalue/coreui/pkg/flow"
)

// WiringGap describes a reference in a .flow file that has no corresponding
// UI element ID in the compiled .cui blueprint.
type WiringGap struct {
	Line      int
	Col       int
	FlowRef   string // the UI ID referenced in .flow
	BlockKind string // "On" or "Compute"
}

// Error implements the error interface.
func (w *WiringGap) Error() string {
	return fmt.Sprintf(
		"[Flow Error] Line %d, Col %d: WIRING_GAP — On(id=%q) references UI element %q which does not exist in the .cui blueprint",
		w.Line, w.Col, w.FlowRef, w.FlowRef,
	)
}

// Binding is a reactive text binding: a UI element whose displayed value
// mirrors a flow state variable.
type Binding struct {
	ElementID string // the UI element id (from .cui)
	AttrName  string // which attribute holds the binding (e.g. "value")
	VarName   string // the flow state variable name (the part after "flow:")
}

// Options configures code generation.
type Options struct {
	// RendererVar is the JS variable name of the CoreUI renderer instance.
	// Defaults to "_cuiRenderer".
	RendererVar string
}

func (o Options) rendererVar() string {
	if o.RendererVar != "" {
		return o.RendererVar
	}
	return "_cuiRenderer"
}

// Generate validates a FlowDocument against the provided set of UI IDs
// (extracted from the compiled .cui blueprint) and returns the generated JS
// state engine source.
//
// It also accepts a list of Bindings—Text/Input elements whose attribute
// values use the "flow:varname" prefix to declare a live reactive link.
//
// If any On block references a UI ID that is not in uiIDs, a *WiringGap
// error is returned.
func Generate(doc *flow.FlowDocument, uiIDs map[string]bool, bindings []Binding, opts Options) (string, error) {
	if doc == nil {
		return "", nil
	}

	// Validate wiring: every On(id=...) must exist in the .cui blueprint.
	for _, on := range doc.OnBlocks {
		if !uiIDs[on.TargetID] {
			return "", &WiringGap{
				Line:      on.Line,
				Col:       on.Col,
				FlowRef:   on.TargetID,
				BlockKind: "On",
			}
		}
	}

	rv := opts.rendererVar()
	var b strings.Builder

	b.WriteString("// CoreFlow State Engine — generated by corec v1.7.0\n")
	b.WriteString("(function(" + rv + ") {\n")

	// ── State object ─────────────────────────────────────────────────────────
	b.WriteString("  const _state = {\n")
	if doc.State != nil {
		for _, v := range doc.State.Vars {
			jsVal := initialJSValue(v)
			b.WriteString(fmt.Sprintf("    %s: %s,\n", v.Name, jsVal))
		}
	}
	b.WriteString("  };\n\n")

	// ── Pub/sub machinery ─────────────────────────────────────────────────────
	b.WriteString("  const _subs = {};\n\n")
	b.WriteString("  function _get(k) { return _state[k]; }\n")
	b.WriteString("  function _set(k, v) {\n")
	b.WriteString("    _state[k] = v;\n")
	b.WriteString("    (_subs[k] || []).forEach(function(fn) { fn(v); });\n")
	b.WriteString("  }\n")
	b.WriteString("  function _sub(k, fn) {\n")
	b.WriteString("    if (!_subs[k]) _subs[k] = [];\n")
	b.WriteString("    _subs[k].push(fn);\n")
	b.WriteString("  }\n\n")

	// ── Compute blocks ───────────────────────────────────────────────────────
	for _, comp := range doc.Computes {
		safe := safeIdent(comp.Target)
		jsExpr := exprToJS(comp.Expr)
		b.WriteString(fmt.Sprintf("  function _compute_%s() {\n", safe))
		b.WriteString(fmt.Sprintf("    return %s;\n", jsExpr))
		b.WriteString("  }\n")

		deps := comp.Expr.IdentNames()
		// Filter to only state variables that are actually declared.
		stateDeps := filterStateDeps(deps, doc)
		for _, dep := range stateDeps {
			b.WriteString(fmt.Sprintf(
				"  _sub(%q, function() { _set(%q, _compute_%s()); });\n",
				dep, comp.Target, safe,
			))
		}
		b.WriteString("\n")
	}

	// ── Reactive text bindings ────────────────────────────────────────────────
	if len(bindings) > 0 {
		b.WriteString("  // Reactive UI bindings\n")
		for _, bind := range bindings {
			b.WriteString(fmt.Sprintf(
				"  _sub(%q, function(v) {\n    var _el = %s.getById(%q);\n    if (_el) _el.textContent = String(v);\n  });\n",
				bind.VarName, rv, bind.ElementID,
			))
		}
		b.WriteString("\n")
	}

	// ── Event listeners from On blocks ───────────────────────────────────────
	if len(doc.OnBlocks) > 0 {
		b.WriteString("  // Event listeners\n")
		for i, on := range doc.OnBlocks {
			varName := fmt.Sprintf("_el%d", i)
			b.WriteString(fmt.Sprintf("  var %s = %s.getById(%q);\n", varName, rv, on.TargetID))
			b.WriteString(fmt.Sprintf("  if (%s) {\n", varName))
			b.WriteString(fmt.Sprintf("    %s.addEventListener(%q, function() {\n", varName, on.Event))
			for _, stmt := range on.Statements {
				writeStatement(&b, stmt, "      ")
			}
			b.WriteString("    });\n")
			b.WriteString(fmt.Sprintf("  } else {\n    console.warn(%q);\n  }\n",
				fmt.Sprintf("CoreFlow: element %q not found — On handler skipped", on.TargetID)))
		}
		b.WriteString("\n")
	}

	// ── Expose public API ────────────────────────────────────────────────────
	b.WriteString("  window.CoreFlowState = { get: _get, set: _set, subscribe: _sub };\n")
	b.WriteString("})(" + rv + ");\n")

	return b.String(), nil
}

// CollectUIIDs traverses a compiled generator.Output-like JSON structure to
// collect all component IDs. This package does not depend on pkg/generator to
// avoid circular imports; callers pass the set of IDs directly.

// CollectBindings scans a compiled JSON blueprint (as a generic map) and
// returns all elements whose string attributes have a "flow:" prefix.
// The blueprint should be the map[string]any decoded from the JSON output.
func CollectBindings(tree map[string]any) []Binding {
	var bindings []Binding
	collectBindingsFromNode(tree, &bindings)
	return bindings
}

func collectBindingsFromNode(node map[string]any, out *[]Binding) {
	id, _ := node["id"].(string)
	attrs, _ := node["attributes"].(map[string]any)
	if id != "" && attrs != nil {
		for attrName, attrVal := range attrs {
			s, ok := attrVal.(string)
			if ok && strings.HasPrefix(s, "flow:") {
				varName := strings.TrimPrefix(s, "flow:")
				if varName != "" {
					*out = append(*out, Binding{
						ElementID: id,
						AttrName:  attrName,
						VarName:   varName,
					})
				}
			}
		}
	}

	children, _ := node["children"].([]any)
	for _, child := range children {
		if childMap, ok := child.(map[string]any); ok {
			collectBindingsFromNode(childMap, out)
		}
	}
}

// ── internal helpers ─────────────────────────────────────────────────────────

// initialJSValue returns the JavaScript initial-value literal for a VarDecl.
func initialJSValue(v *flow.VarDecl) string {
	switch v.Kind {
	case flow.VarKindList:
		return "[]"
	case flow.VarKindMap:
		return "{}"
	}
	// VarKindVar — use the Init expression.
	if v.Init.IsEmpty() {
		return "null"
	}
	return exprToJS(v.Init)
}

// exprToJS converts a flow.Expr to a JavaScript expression string.
// Identifier tokens are emitted as _state.<name> because, by design, all
// identifiers that appear in CoreFlow expressions must refer to declared state
// variables — the flow DSL has no concept of local bindings or JS built-ins.
// Any identifier that is not in the State block will simply resolve to
// _state.<name> at runtime (which will be undefined), consistent with the
// "no implicit magic" architecture principle.
func exprToJS(expr flow.Expr) string {
	if len(expr) == 0 {
		return "undefined"
	}

	parts := make([]string, 0, len(expr))
	for _, tok := range expr {
		switch tok.Kind {
		case flow.TokIdent:
			parts = append(parts, "_state."+tok.Val)
		case flow.TokStr:
			parts = append(parts, jsStringLiteral(tok.Val))
		case flow.TokInt, flow.TokFloat:
			parts = append(parts, tok.Val)
		case flow.TokBool:
			parts = append(parts, tok.Val)
		case flow.TokOp:
			parts = append(parts, tok.Val)
		}
	}
	return strings.Join(parts, " ")
}

// jsStringLiteral returns tok wrapped in JS double quotes with escaping.
func jsStringLiteral(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return `"` + s + `"`
}

// safeIdent converts a string to a safe JS identifier fragment.
func safeIdent(s string) string {
	var b strings.Builder
	for _, ch := range s {
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') || ch == '_' {
			b.WriteRune(ch)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String()
}

// filterStateDeps returns the subset of idents that are declared state variables.
func filterStateDeps(idents []string, doc *flow.FlowDocument) []string {
	if doc.State == nil {
		return nil
	}
	declared := map[string]bool{}
	for _, v := range doc.State.Vars {
		declared[v.Name] = true
	}
	var result []string
	seen := map[string]bool{}
	for _, ident := range idents {
		if declared[ident] && !seen[ident] {
			seen[ident] = true
			result = append(result, ident)
		}
	}
	sort.Strings(result)
	return result
}

// writeStatement writes a single statement as JS to the builder with indentation.
func writeStatement(b *strings.Builder, stmt flow.Statement, indent string) {
	switch stmt.Kind {
	case flow.StmtSet:
		jsVal := exprToJS(stmt.Value)
		b.WriteString(fmt.Sprintf("%s_set(%q, %s);\n", indent, stmt.VarName, jsVal))

	case flow.StmtAdd:
		jsAmount := exprToJS(stmt.Amount)
		b.WriteString(fmt.Sprintf(
			"%s_set(%q, (_get(%q)||0) + (%s));\n",
			indent, stmt.VarName, stmt.VarName, jsAmount,
		))

	case flow.StmtToggle:
		b.WriteString(fmt.Sprintf(
			"%s_set(%q, !_get(%q));\n",
			indent, stmt.VarName, stmt.VarName,
		))

	case flow.StmtIf:
		condJS := conditionToJS(stmt.Condition)
		b.WriteString(fmt.Sprintf("%sif (%s) {\n", indent, condJS))
		for _, child := range stmt.Then {
			writeStatement(b, child, indent+"  ")
		}
		if len(stmt.Else) > 0 {
			b.WriteString(fmt.Sprintf("%s} else {\n", indent))
			for _, child := range stmt.Else {
				writeStatement(b, child, indent+"  ")
			}
		}
		b.WriteString(fmt.Sprintf("%s}\n", indent))

	case flow.StmtService:
		// call_service dispatches a custom DOM event so the Go backend layer
		// can listen via the app: protocol — out-of-scope for freeform JS.
		// Build a sorted-key param object literal for deterministic output.
		keys := make([]string, 0, len(stmt.Params))
		for k := range stmt.Params {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		var paramParts []string
		for _, k := range keys {
			paramParts = append(paramParts, fmt.Sprintf("%s: %s", k, exprToJS(stmt.Params[k])))
		}
		paramsJS := "{" + strings.Join(paramParts, ", ") + "}"
		b.WriteString(fmt.Sprintf(
			"%sdocument.dispatchEvent(new CustomEvent(\"coreflow:service\", { detail: { service: %s, params: %s } }));\n",
			indent, jsStringLiteral(stmt.Service), paramsJS,
		))
	}
}

// conditionToJS converts a flow.Condition to a JavaScript boolean expression.
func conditionToJS(cond flow.Condition) string {
	left := exprToJS(cond.Left)
	right := exprToJS(cond.Right)
	return fmt.Sprintf("%s %s %s", left, cond.Op, right)
}
